#!/bin/sh

# Viewing Site
# https://coronabeds.jantasamvad.org/beds.html
# Api
# https://coronabeds.jantasamvad.org/covid-info.js

DataFile=delhi.tsv
TabSpace="	"

shCat () {
	while IFS= read _Line; do
		printf "%s\n" "$_Line"
	done
}


Data=$(curl -s "https://coronabeds.jantasamvad.org/covid-info.js" | 
	sed '
		1c\{
		$c\}
				' | jq -r ' .beds|to_entries|.[]|select(.key != "All")|
		[.key,.value.vacant,.value.total,.value.last_updated_at,.value.type]|@tsv')


while IFS=$TabSpace read Hospital Vacant Total Update Type; do
	Update=$(date -d "${Update#*,} ${Update%,*}" )
	shCat <<-EOF
	Hospital: $Hospital
	Vacant: $Vacant
	Total: $Total
	Update: $Update
	Type: $Type

	EOF
done <<EOF
$Data
EOF
