#!/bin/sh

curl -L -s "https://bbmpgov.com/chbms" |
	sed -E  -n '
		/>Government Hospitals \(Covid Beds\)<\/h4>$/{
		:loop
		n
		/<td>/{
		s/.*<td>(.*)<\/td>.*/Hospital: \1/
		/^Hospital: [[:space:]]*$/b loop
		p
		H
		n
		n
		n
		n
		n
		n
		n
		n
		n
		n
		n
		n
		n
		n
		n
		s/.*<td[^>]*>(.*)<\/td>.*/Vacant: \1/p
		a\Type: Government Hospital\n
		}
		/<\/table>$/!{
		b loop
		}

		}

		/>Private Hospitals \(Government Quota Covid Beds\)/{
		:loop2
		n
		/<td>/{
		s/.*<td>(.*)<\/td>.*/Hospital: \1/
		/^Hospital: [[:space:]]*$/b loop2
		p
		H
		n
		n
		n
		n
		n
		n
		n
		n
		n
		n
		n
		n
		n
		n
		n
		s/.*<td[^>]*>(.*)<\/td>.*/Vacant: \1/p
		a\Type: Private Hospital\n
		}
		/<\/table>$/!{
		b loop2
		}
		}

		/>Private Medical Colleges \(Government Quota Covid Beds\)/{
		:loop3
		n
		/<td>/{
		s/.*<td>(.*)<\/td>.*/Hospital: \1/
		/^Hospital: [[:space:]]*$/b loop3
		p
		H
		n
		n
		n
		n
		n
		n
		n
		n
		n
		n
		n
		n
		n
		n
		n
		s/.*<td[^>]*>(.*)<\/td>.*/Vacant: \1/p
		a\Type: Private Medical College\n
		}
		/<\/table>$/!{
		b loop3
		}
		}

		/>Government Covid Care Centers \(CCC\)/{
		:loop4
		n
		/<td>/{
		s/.*<td>(.*)<\/td>.*/Hospital: \1/
		/^Hospital: [[:space:]]*$/b loop4
		p
		H
		n
		n
		s/.*<td[^>]*>(.*)<\/td>.*/Vacant: \1/p
		a\Type: Govt Covid Care Centers\n
		}
		/<\/table>$/!{
		b loop4
		}
		}
	'

