#!/bin/sh

# $1 determines what to be scraped
# if empty then it will scrape get all hospital data
# o - O2 supply
# i - ICU beds
# m - mild symptomatic case beds

case $1 in
	'')	tid=1;;
	o)	tid=4;;
	i)	tid=6;;
	m)	tid=5;;
	*)	exit 1;;
esac

curl -s "https://vmc.gov.in/Covid19VadodaraApp/HospitalBedsDetails.aspx?tid=$tid" | sed  -E '
/^[[:space:]]*<td align="left" width="200">/!d
s/<[^>]*>/:/g
s/::*/:/g
s/^[[:space:]]*://
s/^([^:]*):([^:]*):([^:]*):([^:]*):([^:]*):([^:]*):([^:]*):.*/Hospital: \1\nAddress: \2\nTotal: \3\nOccupied: \4\nVacant: \5\nNodalOfficerName: \6\nMobileNo: \7\n/'

